source "https://rubygems.org"
  gem "rails", "~> 6.1.3"
  gem "redis", "~> 4.2.5"
  gem "cable_ready", "~> 5.0.0.pre0"
  gem "stimulus_reflex", "~> 3.5.0.pre0"
  gem "puma", "~> 5.2.2"
  gem "activerecord-nulldb-adapter"  